package com.clinmind.runtime.audit;

public enum AuditActionType {
    CREATE_RUNTIME,
    CONTINUE_RUNTIME,
    CREATE_EVALUATION_RUN,
    GENERATE_CANDIDATES,
    REVIEW_EXPERIENCE_CANDIDATE,
    REVIEW_TRAINING_CANDIDATE,
    QUERY_CONSOLE_RUNTIME,
    QUERY_CONSOLE_EVALUATION
}
