package com.clinmind.runtime.audit;

public enum AuditResourceType {
    RUNTIME,
    EVALUATION_RUN,
    CANDIDATE_GENERATION,
    EXPERIENCE_CANDIDATE,
    TRAINING_EXAMPLE_CANDIDATE,
    CANDIDATE_REVIEW,
    AUDIT_LOG,
    AGENT_EXECUTION,
    EVIDENCE_RETRIEVAL,
    GRAPH_EVIDENCE
}
