package com.clinmind.runtime.audit;

public enum AuditActionType {
    CREATE_RUNTIME,
    CONTINUE_RUNTIME,
    CREATE_EVALUATION_RUN,
    GENERATE_CANDIDATES,
    REVIEW_EXPERIENCE_CANDIDATE,
    REVIEW_TRAINING_CANDIDATE,
    QUERY_CONSOLE_RUNTIME,
    QUERY_CONSOLE_EVALUATION,
    QUERY_CONSOLE_CANDIDATE,
    QUERY_CONSOLE_AUDIT,
    RUN_AGENT_INQUIRY_PLANNING,
    QUERY_AGENT_EXECUTION,
    QUERY_AGENT_REGISTRY,
    RUN_EVIDENCE_RETRIEVAL,
    QUERY_EVIDENCE_RETRIEVAL,
    QUERY_EVIDENCE_CORPUS,
    RUN_GRAPH_EVIDENCE,
    QUERY_GRAPH_EVIDENCE,
    QUERY_KG_LITE_GRAPH,
    RUN_PYTHON_PROVIDER,
    QUERY_PYTHON_PROVIDER
}
