package com.clinmind.runtime.candidate;

public enum CandidateSkippedReason {
    PASSED_CASE_SKIPPED,
    NOT_APPLICABLE_METRIC_SKIPPED,
    MINOR_FAILURE_DISABLED,
    DUPLICATE_CANDIDATE_SKIPPED,
    MAX_CANDIDATES_PER_CASE_REACHED,
    UNSUPPORTED_METRIC_SKIPPED,
    RUNTIME_CASE_EXECUTION_MISSING
}
