package com.clinmind.runtime.candidate;

public enum TrainingTaskType {
    INTENT_CLASSIFICATION,
    SYMPTOM_GROUP_CLASSIFICATION,
    RISK_SIGNAL_CLASSIFICATION,
    CASE_FRAME_EXTRACTION,
    PATIENT_SAFE_REWRITE,
    DDX_EXPECTATION,
    NEXT_ACTION_EXPECTATION,
    TRACE_QUALITY_EXPECTATION,
    ASSET_TRACE_EXPECTATION
}
